import { useEffect, useState } from 'react';
import api from '../api';

const emptyForm = { title: '', type: 'Manhwa', status: 'draft', score: 0, cover: '', author: '', description: '', genres: '' };
export default function AdminPage() {
  const [stats, setStats] = useState({ users: 0, series: 0, chapters: 0 });
  const [items, setItems] = useState([]); const [users, setUsers] = useState([]); const [form, setForm] = useState(emptyForm);
  const [chapter, setChapter] = useState({ seriesId: '', number: 1, title: '', pages: '' }); const [message, setMessage] = useState('');
  const load = async () => { const [s, c, u] = await Promise.all([api.get('/admin/stats'), api.get('/admin/series'), api.get('/admin/users')]); setStats(s.data); setItems(c.data.items); setUsers(u.data.items); if (!chapter.seriesId && c.data.items[0]) setChapter((x) => ({ ...x, seriesId: c.data.items[0].id })); };
  useEffect(() => { load().catch((e) => setMessage(e.response?.data?.message || 'Error cargando panel')); }, []);
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const createSeries = async (e) => { e.preventDefault(); await api.post('/admin/series', { ...form, score: Number(form.score), genres: form.genres.split(',').map((x) => x.trim()).filter(Boolean) }); setForm(emptyForm); setMessage('Manga creado.'); load(); };
  const addChapter = async (e) => { e.preventDefault(); await api.post(`/admin/series/${chapter.seriesId}/chapters`, { number: Number(chapter.number), title: chapter.title, pages: chapter.pages.split('\n').map((x) => x.trim()).filter(Boolean), published: true }); setChapter({ ...chapter, number: chapter.number + 1, title: '', pages: '' }); setMessage('Capítulo guardado.'); load(); };
  const removeSeries = async (id) => { if (!window.confirm('¿Eliminar este manga y sus capítulos?')) return; await api.delete(`/admin/series/${id}`); load(); };
  return <section><div className="hero-panel"><div><p className="eyebrow">Solo administradores</p><h1>Panel de administración</h1><p>Sube y organiza tu catálogo desde un solo lugar.</p></div></div>
    <div className="admin-stats">{[['Usuarios', stats.users], ['Mangas publicados', stats.series], ['Capítulos', stats.chapters]].map(([label, value]) => <div className="profile-card" key={label}><span className="eyebrow">{label}</span><strong className="big-number">{value}</strong></div>)}</div>
    {message && <div className="success-box">{message}</div>}
    <div className="admin-grid"><form className="profile-card admin-form" onSubmit={createSeries}><h2>Agregar manga</h2><input name="title" placeholder="Título" value={form.title} onChange={update} required /><select name="type" value={form.type} onChange={update}><option>Manhwa</option><option>Manga</option><option>Manhua</option><option>Webtoon</option></select><input name="author" placeholder="Autor" value={form.author} onChange={update} /><input name="cover" placeholder="URL de portada" value={form.cover} onChange={update} /><input name="genres" placeholder="Géneros separados por coma" value={form.genres} onChange={update} /><textarea name="description" placeholder="Descripción" value={form.description} onChange={update} /><select name="status" value={form.status} onChange={update}><option value="draft">Borrador</option><option value="published">Publicado</option></select><button className="primary-button">Guardar manga</button></form>
      <form className="profile-card admin-form" onSubmit={addChapter}><h2>Agregar capítulo</h2><select value={chapter.seriesId} onChange={(e) => setChapter({ ...chapter, seriesId: e.target.value })}>{items.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input type="number" min="1" value={chapter.number} onChange={(e) => setChapter({ ...chapter, number: e.target.value })} /><input placeholder="Nombre del capítulo" value={chapter.title} onChange={(e) => setChapter({ ...chapter, title: e.target.value })} required /><textarea placeholder="Una URL de página por línea" value={chapter.pages} onChange={(e) => setChapter({ ...chapter, pages: e.target.value })} required /><button className="primary-button">Guardar capítulo</button></form></div>
    <div className="profile-card admin-table"><h2>Catálogo</h2>{items.map((item) => <div className="admin-row" key={item.id}><div><strong>{item.title}</strong><span>{item.type} · {item.status} · {item.chapters.length} capítulos</span></div><button className="danger-button" onClick={() => removeSeries(item.id)}>Eliminar</button></div>)}</div>
    <div className="profile-card admin-table"><h2>Usuarios</h2>{users.map((item) => <div className="admin-row" key={item.id}><div><strong>{item.name}</strong><span>{item.email} · {item.role}</span></div></div>)}</div>
  </section>;
}
